import Navigation from '@/componets/Navigation'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My App NextJs',
  description: 'Generated by create next app',
  keywords: 'next, react, qpp'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <link rel='stylesheet' href='https://bootswatch.com/5/flatly/bootstrap.min.css' />
      
    </head>
    {/* className={inter.className} */}
      <body>
          <Navigation/>
          <div className='container p-4'>
            {children}
          </div>
      </body>
    </html>
  )
}
